---
sudo: false
language: objective-c

# Reference for OS X Versions:
# https://docs.travis-ci.com/user/reference/osx/#macos-version
matrix:
  include:
    # Mojave (10.14)
    - os: osx
      osx_image: xcode11.3
    # High Sierra (10.13)
    - os: osx
      osx_image: xcode10.1

install:
  # Install test requirements
  - pip install -r tests/requirements.txt

  # Print Ansible version
  - ansible --version

script:
  - tests/run_tests.sh --check-apply

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
