---
- name: "Desktop Hot Corners - Set top left corner action 1/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-tl-corner', type: int, value: "{{DesktopHotCorners_TopLeft}}" }
  when: DesktopHotCorners_TopLeft is defined

- name: "Desktop Hot Corners - Set top left corner action 2/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-tl-modifier', type: int, value: 0 }
  when: DesktopHotCorners_TopLeft is defined

- name: "Desktop Hot Corners - Set top right corner action 1/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-tr-corner', type: int, value: "{{DesktopHotCorners_TopRight}}" }
  when: DesktopHotCorners_TopRight is defined

- name: "Desktop Hot Corners - Set top right corner action 2/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-tr-modifier', type: int, value: 0 }
  when: DesktopHotCorners_TopRight is defined

- name: "Desktop Hot Corners - Set bottom left corner action 1/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-bl-corner', type: int, value: "{{DesktopHotCorners_BottomLeft}}" }
  when: DesktopHotCorners_BottomLeft is defined

- name: "Desktop Hot Corners - Set bottom left corner action 2/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-bl-modifier', type: int, value: 0 }
  when: DesktopHotCorners_BottomLeft is defined

- name: "Desktop Hot Corners - Set bottom right corner action 1/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-br-corner', type: int, value: "{{DesktopHotCorners_BottomRight}}" }
  when: DesktopHotCorners_BottomRight is defined

- name: "Desktop Hot Corners - Set bottom right corner action 2/2"
  osx_defaults: { domain: 'com.apple.dock', key: 'wvous-br-modifier', type: int, value: 0 }
  when: DesktopHotCorners_BottomRight is defined

